name: PoC Default

on:
  push:
    paths:
    - 'poc/**'
    - '!poc/README.md'

defaults:
  run:
    working-directory: poc

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Test building the application
      run: npm run build
    - name: Run the unit tests
      run: npm test
